name: ci

on:
  push:
    branches:
      - 'main'
      - 'dev'

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Download files
      run: |
        pip3 install gdown
        ~/.local/bin/gdown https://drive.google.com/uc?id=197kgRfSomZzaSbRrjWTx614le2qN-oxx
        unzip planning_simulator_sample_map.zip
        mv lanelet2_map.osm data/psim/
        mv pointcloud_map.pcd data/psim/
    -
      name: Build image
      run: |
        docker build -t ghcr.io/autocore-ai/data-foxy .
        docker push ghcr.io/autocore-ai/data-foxy
